openapi: 3.0.3
info:
  title: Context Analyzer Agent Contract
  description: |
    Contract for the Context Analyzer Agent that performs codebase analysis and summarization.
    Scans relevant files, identifies dependencies, creates structured summaries,
    and provides semantic context retrieval for grounded decision-making.
  version: 1.0.0

paths:
  /analyze:
    post:
      summary: Analyze codebase context
      description: |
        Scans codebase for files relevant to current task, maps dependencies,
        identifies existing patterns, generates semantic embeddings, and creates
        structured summary for agent consumption.
      operationId: analyzeContext
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContextAnalysisRequest'
            examples:
              newFeature:
                summary: Analyze context for new feature
                value:
                  agent_id: architecture.context_analyzer
                  task_id: 550e8400-e29b-41d4-a716-446655440000
                  phase: specification
                  task_description: Implement user authentication system
                  search_keywords: [authentication, user, login, security, session]
                  scan_paths:
                    - /workspaces/sdd-agentic-framework/.claude/agents
                    - /workspaces/sdd-agentic-framework/specs
                    - /workspaces/sdd-agentic-framework/.specify/memory
                  max_results: 10
                  performance_target_ms: 2000
      responses:
        '200':
          description: Context analysis completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContextAnalysisResponse'
              examples:
                success:
                  summary: Context retrieved successfully
                  value:
                    agent_id: architecture.context_analyzer
                    task_id: 550e8400-e29b-41d4-a716-446655440000
                    success: true
                    output_data:
                      relevant_files:
                        - /workspaces/sdd-agentic-framework/.specify/memory/constitution.md
                        - /workspaces/sdd-agentic-framework/specs/000-agent-framework/spec.md
                        - /workspaces/sdd-agentic-framework/.claude/agents/security/security-specialist.md
                      file_summaries:
                        constitution.md: 14 enforceable principles including security requirements
                        000-agent-framework/spec.md: Framework architecture with agent delegation
                        security-specialist.md: Security review and vulnerability assessment agent
                      existing_patterns:
                        - Agent Delegation Protocol
                        - Contract-First Design
                        - Input Validation (Principle XI)
                      dependencies:
                        security-specialist.md: [constitution.md, agent-collaboration-triggers.md]
                      related_specs:
                        - specs/000-agent-framework/spec.md
                      constitutional_status:
                        Principle I: true
                        Principle XI: true
                      retrieval_latency_ms: 487
                      retrieval_method: semantic_embedding
                    reasoning: Found existing security patterns and constitutional requirements for input validation
                    confidence: 0.89
                    next_actions:
                      - Reference Principle XI for authentication validation
                      - Consult security-specialist agent for review
                    timestamp: '2025-11-10T13:00:00Z'

  /search:
    post:
      summary: Semantic search codebase
      description: |
        Performs semantic similarity search over indexed codebase documents
        using embedding-based matching. Falls back to keyword search if timeout.
      operationId: searchContext
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContextSearchRequest'
      responses:
        '200':
          description: Search completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContextSearchResponse'

components:
  schemas:
    ContextAnalysisRequest:
      type: object
      required:
        - agent_id
        - task_id
        - phase
        - task_description
        - search_keywords
        - scan_paths
      properties:
        agent_id:
          type: string
          pattern: '^architecture\.context_analyzer$'
        task_id:
          type: string
          format: uuid
        phase:
          type: string
          enum: [specification, planning, implementation, validation]
        task_description:
          type: string
          description: Human-readable task description
        search_keywords:
          type: array
          items:
            type: string
          description: Keywords for context retrieval
        scan_paths:
          type: array
          items:
            type: string
          description: Directories to scan for relevant files
        max_results:
          type: integer
          minimum: 1
          maximum: 50
          default: 10
          description: Maximum files to return
        performance_target_ms:
          type: integer
          minimum: 100
          maximum: 5000
          default: 2000
          description: Target retrieval latency

    ContextAnalysisResponse:
      type: object
      required:
        - agent_id
        - task_id
        - success
        - output_data
        - reasoning
        - confidence
        - next_actions
        - timestamp
      properties:
        agent_id:
          type: string
        task_id:
          type: string
          format: uuid
        success:
          type: boolean
        output_data:
          $ref: '#/components/schemas/ContextSummary'
        reasoning:
          type: string
        confidence:
          type: number
          minimum: 0.0
          maximum: 1.0
        next_actions:
          type: array
          items:
            type: string
        timestamp:
          type: string
          format: date-time

    ContextSummary:
      type: object
      required:
        - relevant_files
        - file_summaries
        - existing_patterns
        - retrieval_latency_ms
        - retrieval_method
      properties:
        relevant_files:
          type: array
          items:
            type: string
          description: Absolute paths to relevant files
        file_summaries:
          type: object
          additionalProperties:
            type: string
          description: Brief summary per file
        existing_patterns:
          type: array
          items:
            type: string
          description: Architectural patterns identified
        dependencies:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: File dependency graph
        related_specs:
          type: array
          items:
            type: string
          description: Related feature specifications
        constitutional_status:
          type: object
          additionalProperties:
            type: boolean
          description: Principle compliance per area
        retrieval_latency_ms:
          type: integer
          description: Time taken for retrieval
        retrieval_method:
          type: string
          enum: [semantic_embedding, keyword_fallback, cached]
          description: Method used for retrieval
        embedding_vector:
          type: array
          items:
            type: number
          nullable: true
          description: Semantic embedding (384-dim)
        generated_at:
          type: string
          format: date-time

    ContextSearchRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: Search query
        max_results:
          type: integer
          minimum: 1
          maximum: 50
          default: 10
        timeout_ms:
          type: integer
          minimum: 100
          maximum: 5000
          default: 2000

    ContextSearchResponse:
      type: object
      required:
        - results
        - latency_ms
        - method
      properties:
        results:
          type: array
          items:
            type: object
            properties:
              file_path:
                type: string
              relevance_score:
                type: number
                minimum: 0.0
                maximum: 1.0
              summary:
                type: string
        latency_ms:
          type: integer
        method:
          type: string
          enum: [semantic_embedding, keyword_fallback]
        timeout_fallback:
          type: boolean
          default: false
