openapi: 3.0.3
info:
  title: Router Agent Contract
  description: |
    Contract for the Intelligent Router Agent that makes orchestration decisions.
    Analyzes task complexity and state to determine appropriate agent selection,
    execution strategy, and refinement approach on failures.
  version: 1.0.0

paths:
  /route:
    post:
      summary: Determine optimal agent routing
      description: |
        Analyzes current task state and determines which agents should be invoked,
        in what order, and with what strategy for handling failures.
      operationId: routeTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoutingRequest'
            examples:
              multiDomainFeature:
                summary: Route multi-domain feature
                value:
                  agent_id: architecture.router
                  task_id: 550e8400-e29b-41d4-a716-446655440000
                  phase: implementation
                  task_description: Implement user authentication with frontend and backend
                  domains_detected: [frontend, backend, security]
                  current_state:
                    completed_agents: []
                    failed_agents: []
                  context:
                    spec_path: /workspaces/sdd-agentic-framework/specs/002-auth/spec.md
                    plan_path: /workspaces/sdd-agentic-framework/specs/002-auth/plan.md
      responses:
        '200':
          description: Routing decision generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoutingResponse'
              examples:
                dagExecution:
                  summary: DAG execution with dependencies
                  value:
                    agent_id: architecture.router
                    task_id: 550e8400-e29b-41d4-a716-446655440000
                    success: true
                    output_data:
                      selected_agents:
                        - engineering.backend
                        - engineering.frontend
                        - security.specialist
                      execution_strategy: dag
                      dependency_graph:
                        engineering.backend: []
                        security.specialist: [engineering.backend]
                        engineering.frontend: [engineering.backend, security.specialist]
                      refinement_strategy: ROUTE_TO_DEBUG
                      parallel_execution_opportunities: []
                    reasoning: |
                      Backend API must be implemented first to define authentication contract.
                      Security specialist validates backend implementation.
                      Frontend depends on both backend contract and security validation.
                    confidence: 0.92
                    next_actions:
                      - Invoke engineering.backend agent
                      - Wait for completion before invoking security.specialist
                    timestamp: '2025-11-10T11:00:00Z'

        '400':
          description: Invalid request parameters

components:
  schemas:
    RoutingRequest:
      type: object
      required:
        - agent_id
        - task_id
        - phase
        - task_description
        - domains_detected
        - current_state
      properties:
        agent_id:
          type: string
          pattern: '^architecture\.router$'
        task_id:
          type: string
          format: uuid
        phase:
          type: string
          enum: [specification, planning, implementation, validation]
        task_description:
          type: string
          description: Human-readable description of task
        domains_detected:
          type: array
          items:
            type: string
          description: Domains identified in task (frontend, backend, database, etc.)
        current_state:
          type: object
          properties:
            completed_agents:
              type: array
              items:
                type: string
              description: Agents that have already completed
            failed_agents:
              type: array
              items:
                type: object
                properties:
                  agent_id:
                    type: string
                  error:
                    type: string
                  attempts:
                    type: integer
        context:
          $ref: '#/components/schemas/AgentContext'

    RoutingResponse:
      type: object
      required:
        - agent_id
        - task_id
        - success
        - output_data
        - reasoning
        - confidence
        - next_actions
        - timestamp
      properties:
        agent_id:
          type: string
        task_id:
          type: string
          format: uuid
        success:
          type: boolean
        output_data:
          $ref: '#/components/schemas/RoutingDecision'
        reasoning:
          type: string
        confidence:
          type: number
          minimum: 0.0
          maximum: 1.0
        next_actions:
          type: array
          items:
            type: string
        timestamp:
          type: string
          format: date-time

    RoutingDecision:
      type: object
      required:
        - selected_agents
        - execution_strategy
        - refinement_strategy
      properties:
        selected_agents:
          type: array
          items:
            type: string
          description: Agent IDs to invoke
          minItems: 1
        execution_strategy:
          type: string
          enum: [sequential, parallel, dag]
          description: How to execute selected agents
        dependency_graph:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: Agent dependencies (required if strategy is dag)
          nullable: true
        refinement_strategy:
          type: string
          enum: [ADD_STEP, TRUNCATE_FROM, ROUTE_TO_DEBUG, RETRY_WITH_FEEDBACK]
          description: Strategy on failure
          nullable: true
        parallel_execution_opportunities:
          type: array
          items:
            type: string
          description: Agents that can be executed in parallel

    AgentContext:
      type: object
      properties:
        spec_path:
          type: string
          nullable: true
        plan_path:
          type: string
          nullable: true
        previous_outputs:
          type: array
          items:
            type: object
        cumulative_feedback:
          type: array
          items:
            type: string
